apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: accounting
type: Opaque
stringData:
  DB_USERNAME: sinergi
  DB_PASSWORD: "123"
  APP_KEY: base64:EEJr0Cs5v7gwAy5mMk4SxQd0w7J7U1idY6rEqE+Fax8=
