# =========================
# Frontend - Vue
# =========================
frontend:
  replicaCount: 2

  image:
    repository: hudaaaja/vue-frontend
    tag: "1.0.1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80


# =========================
# Backend - Laravel
# =========================
laravel:
  replicaCount: 2

  image:
    repository: hudaaaja/laravel-backend
    tag: "1.0.1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  env:
    APP_ENV: production
    APP_DEBUG: "false"
    APP_URL: http://laravel


# =========================
# PostgreSQL
# =========================
postgres:
  database: sinergi
  username: sinergi
  password: "123"

  service:
    port: 5432

  storage:
    size: 5Gi

  image:
    repository: pgvector/pgvector
    tag: "pg17"
    pullPolicy: IfNotPresent

# =========================
# Ingress
# =========================
ingress:
  enabled: true

  host: accounting.mhuda.my.id
